name: 'test my project'
on: [push]
jobs:
 checks:
  runs-on: ubuntu-latest
  steps:
  - name: Begin
    uses: actions/checkout@v3
  - name: Setup Python
    uses: actions/setup-python@v2
  - name: Setup dependencies
    run: pip install -r requirements.txt
  - name: Run tests
    run: ls